name: Check NFL Teams Data Updates

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'
      
      - name: Install R packages
        run: |
          install.packages(c('nflreadr', 'digest'), repos = 'https://cloud.r-project.org')
        shell: Rscript {0}
      
      - name: Check for updates
        id: check
        run: |
          # Load current teams data
          teams <- nflreadr::load_teams()
          
          # Create hash of the data
          current_hash <- digest::digest(teams, algo="sha256")
          
          # Read previous hash if it exists
          prev_hash <- ""
          if (file.exists("teams_hash.txt")) {
            prev_hash <- readLines("teams_hash.txt")[1]
          }
          
          # Compare hashes
          if (current_hash != prev_hash) {
            # Save new hash
            writeLines(current_hash, "teams_hash.txt")
            
            # Set output for next step
            cat("::set-output name=updated::true")
          } else {
            cat("::set-output name=updated::false")
          }
        shell: Rscript {0}
      
      - name: Trigger Databricks Job
        if: steps.check.outputs.updated == 'true'
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
               "${DATABRICKS_HOST}/api/2.0/jobs/run-now" \
               -d "{\"job_id\": \"${DATABRICKS_JOB_ID}\"}"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_JOB_ID: ${{ secrets.DATABRICKS_JOB_ID }}